formats:
  "date": "yyyy-MM-dd"
  "time": "HH:mm:ss"

scoreboard-settings:
  updateInterval: 10 # Seconds
  displayName: "&6&lScoreboard"
vault:
  symbole: '$'

# Update Settings
autoDownload: false  # Set to true to automatically download and install updates