formats:
  "date": "yyyy-MM-dd"
  "time": "HH:mm:ss"

scoreboard-settings:
  updateInterval: 10 # Seconds
  displayName: "&6&lScoreboard"
vault:
  symbole: '$'

scoreboard:
  "player":
    name: "&a&lPlayer&r » "
    value: "%player%"
  "placeHolder1":
    name: "placeholder"
    value: "--------------------------------"
  "ping":
    name: "&a&lPing&r » "
    value: "%ping%"
  "world":
    name: "&a&lWorld&r » "
    value: "%world%"
  "coordinates":
    name: "&a&lCoordinates&r » "
    value: "%coordinates%"
  "level":
    name: "&a&lLevel&r » "
    value: "%level%"
  "player-time":
    name: "&a&lPlayer Time&r » "
    value: "%player_world_time%"
  "money":
    name: "&a&lMoney&r » "
    value: "%money%%currency%"
  "tps":
    name: "&a&lTPS&r » "
    value: "%tps%"
  "player-version":
    name: "&a&lPlayer Version&r » "
    value: "%player_version%"
  "placeHolder2":
    name: "placeholder"
    value: "--------------------------------"
  "online-players":
    name: "&a&lOnline Players&r » "
    value: "%online% / %max_players%"
  "server-name":
    name: "&a&lServerName&r » "
    value: "&6Your Server Name"

# Update Settings
autoDownload: false  # Set to true to automatically download and install updates