name: CustomScoreboard
version: ${project.version}
main: ch.framedev.customScoreboard.CustomScoreboard
api-version: '1.21'
description: A custom scoreboard plugin for Spigot.
author: FrameDev

dependencies:
  - PacketEvents

soft-dependencies:
  - Vault

commands:
  customscoreboard:
    description: A custom scoreboard plugin for Spigot.
    aliases: [cs]
    permission: customscoreboard.command
